import {EnumUserRole, EnumUserStatus, EnumBuyCoinStatus, EnumCoinHistoryStatus} from "./enums";

// Creating an array of three user objects
export const fakeDataUsers = [
  {
    name: "Alice Johnson",
    email: `${EnumUserRole.admin}@gmail.com`,
    role: EnumUserRole.admin,
    permissions: ["read", "write", "delete"],
    id: 1,
    token: "token_123456",
    photo: "https://api.dicebear.com/9.x/dylan/svg?seed=Snuggles&hairColor=000000&mood=happy",
    password: `password${EnumUserRole.admin}`,
    status: EnumUserStatus.active,
    phone: "01125963552",
  },
  {
    name: "Bob Smith",
    email: `${EnumUserRole.user}@gmail.com`,
    role: EnumUserRole.user,
    permissions: ["read"],
    id: 2,
    token: "token_654321",
    photo: "https://api.dicebear.com/9.x/dylan/svg?seed=Dusty&hairColor=000000&mood=happy",
    password: `password${EnumUserRole.user}`,
    status: EnumUserStatus.inactive,
    phone: "0125875220",
  },
];

export const fakeDataBuyCoinHistory = [
  {
    id: 1,
    address: "123 Main St",
    coinAmount: 0.5,
    coinName: "Bitcoin",
    paymentType: "Credit Card",
    status: EnumBuyCoinStatus.completed,
    createdAt: "2024-09-03T12:00:00Z",
  },
  {
    id: 2,
    address: "456 Oak Ave",
    coinAmount: 1.25,
    coinName: "Ethereum",
    paymentType: "PayPal",
    status: EnumBuyCoinStatus.pending,
    createdAt: "2024-09-02T14:30:00Z",
  },
  {
    id: 3,
    address: "789 Pine Rd",
    coinAmount: 0.75,
    coinName: "Litecoin",
    paymentType: "Bank Transfer",
    status: EnumBuyCoinStatus.failed,
    createdAt: "2024-09-01T09:15:00Z",
  },
  {
    id: 4,
    address: "321 Birch Ln",
    coinAmount: 2.0,
    coinName: "Ripple",
    paymentType: "Debit Card",
    status: EnumBuyCoinStatus.completed,
    createdAt: "2024-08-31T16:45:00Z",
  },
  {
    id: 5,
    address: "654 Maple St",
    coinAmount: 0.1,
    coinName: "Bitcoin",
    paymentType: "Bank Transfer",
    status: EnumBuyCoinStatus.pending,
    createdAt: "2024-08-30T10:20:00Z",
  },
  {
    id: 6,
    address: "987 Cedar Blvd",
    coinAmount: 0.3,
    coinName: "Ethereum",
    paymentType: "Credit Card",
    status: EnumBuyCoinStatus.completed,
    createdAt: "2024-08-29T13:05:00Z",
  },
  {
    id: 7,
    address: "741 Walnut Dr",
    coinAmount: 1.5,
    coinName: "Litecoin",
    paymentType: "PayPal",
    status: EnumBuyCoinStatus.failed,
    createdAt: "2024-08-28T08:40:00Z",
  },
];

export const fakeDataSentCoinHistory = [
  {
    id: 1,
    sender: "Alice",
    receiver: "Bob",
    coinAmount: 10,
    coinName: "Bitcoin",
    status: EnumCoinHistoryStatus.accepted,
    createdAt: "2024-09-01T12:00:00Z",
  },
  {
    id: 2,
    sender: "Charlie",
    receiver: "Dana",
    coinAmount: 5,
    coinName: "Ethereum",
    status: EnumCoinHistoryStatus.pending,
    createdAt: "2024-09-02T14:30:00Z",
  },
  {
    id: 3,
    sender: "Eve",
    receiver: "Frank",
    coinAmount: 20,
    coinName: "Litecoin",
    status: EnumCoinHistoryStatus.failed,
    createdAt: "2024-09-02T16:45:00Z",
  },
  {
    id: 4,
    sender: "Grace",
    receiver: "Heidi",
    coinAmount: 8,
    coinName: "Ripple",
    status: EnumCoinHistoryStatus.accepted,
    createdAt: "2024-09-03T09:15:00Z",
  },
  {
    id: 5,
    sender: "Ivan",
    receiver: "Judy",
    coinAmount: 12,
    coinName: "Cardano",
    status: EnumCoinHistoryStatus.pending,
    createdAt: "2024-09-03T11:30:00Z",
  },
  {
    id: 6,
    sender: "Karl",
    receiver: "Liam",
    coinAmount: 7,
    coinName: "Polkadot",
    status: EnumCoinHistoryStatus.accepted,
    createdAt: "2024-09-04T08:00:00Z",
  },
  {
    id: 7,
    sender: "Mona",
    receiver: "Nina",
    coinAmount: 15,
    coinName: "Chainlink",
    status: EnumCoinHistoryStatus.failed,
    createdAt: "2024-09-04T10:20:00Z",
  },
];

export const fakeDataWallets = [
  {
    label: "Select Wallet",
    value: "",
    disabled: true,
  },
  {
    label: "USDT",
    value: "USDT",
  },
  {
    label: "USDC",
    value: "USDC",
  },
  {
    label: "DAI",
    value: "DAI",
  },
];

export const fakeDataMyWallets = [
  {
    id: 1,
    name: "Bitcoin",
    coinType: "BTC",
    balance: 1.2345,
    updatedAt: "2024-09-01",
  },
  {
    id: 2,
    name: "Ethereum",
    coinType: "ETH",
    balance: 10.6789,
    updatedAt: "2024-09-02",
  },
  {
    id: 3,
    name: "Ripple",
    coinType: "XRP",
    balance: 5000.1234,
    updatedAt: "2024-09-03",
  },
  {
    id: 4,
    name: "Litecoin",
    coinType: "LTC",
    balance: 250.5678,
    updatedAt: "2024-09-04",
  },
  {
    id: 5,
    name: "Cardano",
    coinType: "ADA",
    balance: 10000.9876,
    updatedAt: "2024-09-05",
  },
];

export const fakeDataSwapHistory = [
  {
    id: 1,
    fromWallet: "Wallet A",
    toWallet: "Wallet B",
    requestedAmount: 100.0,
    convertedAmount: 98.5,
    rate: 0.985,
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: 2,
    fromWallet: "Wallet C",
    toWallet: "Wallet D",
    requestedAmount: 200.0,
    convertedAmount: 196.0,
    rate: 0.98,
    createdAt: "2024-09-02T11:00:00Z",
  },
  {
    id: 3,
    fromWallet: "Wallet E",
    toWallet: "Wallet F",
    requestedAmount: 150.0,
    convertedAmount: 147.0,
    rate: 0.98,
    createdAt: "2024-09-03T12:00:00Z",
  },
  {
    id: 4,
    fromWallet: "Wallet G",
    toWallet: "Wallet H",
    requestedAmount: 300.0,
    convertedAmount: 294.0,
    rate: 0.98,
    createdAt: "2024-09-04T13:00:00Z",
  },
];

export const fakeDataPlans = [
  {
    id: 1,
    planName: "Silver",
    minimumAmount: "500.00 NEWTKN",
    minimumDuration: "360 days",
    bonusPercentage: "20.00%",
    image: "/Silver.png",
    color: "#dfdfdf",
  },
  {
    id: 2,
    planName: "Gold",
    minimumAmount: "1,000.00 NEWTKN",
    minimumDuration: "30 days",
    bonusPercentage: "0.00%",
    image: "/Gold.png",
    color: "#ffbd25",
  },
  {
    id: 3,
    planName: "Platinum",
    minimumAmount: "2,000.00 NEWTKN",
    minimumDuration: "30 days",
    bonusPercentage: "0.00%",
    image: "/Platinum.png",
    color: "#8d71de",
  },
  {
    id: 4,
    planName: "Basic plan",
    minimumAmount: "0.05 NEWTKN",
    minimumDuration: "15 days",
    bonusPercentage: "1.00%",
    image: "/Basic.png",
    color: "#ffbd25",
  },
];

export const fakeDataReferrals = [
  {id: 1, level1: "Beginner", level2: "Intermediate", level3: "Advanced"},
  {id: 2, level1: "Basic", level2: "Skilled", level3: "Expert"},
  {id: 3, level1: "Entry", level2: "Proficient", level3: "Master"},
];

export const fakeDataReferences = [
  {
    id: 1,
    fullName: "John Doe",
    email: "john.doe@example.com",
    level: "Intermediate",
    joiningDate: "2022-01-15",
    balance: 1500.5,
    isActive: true,
  },
  {
    id: 2,
    fullName: "Jane Smith",
    email: "jane.smith@example.com",
    level: "Advanced",
    joiningDate: "2021-06-23",
    balance: 2300.75,
    isActive: false,
  },
  {
    id: 3,
    fullName: "Alice Johnson",
    email: "alice.johnson@example.com",
    level: "Beginner",
    joiningDate: "2023-03-10",
    balance: 890.0,
    isActive: true,
  },
  {
    id: 4,
    fullName: "Bob Williams",
    email: "bob.williams@example.com",
    level: "Expert",
    joiningDate: "2019-11-04",
    balance: 3200.25,
    isActive: true,
  },
];

export const fakeDataEarnings = [
  {
    id: 1,
    fromChild: "Alice",
    coinAmount: 50,
    coinName: "Bitcoin",
    status: "Completed",
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    fromChild: "Bob",
    coinAmount: 120,
    coinName: "Ethereum",
    status: "Pending",
    createdAt: "2024-02-05",
  },
  {
    id: 3,
    fromChild: "Charlie",
    coinAmount: 75,
    coinName: "Litecoin",
    status: "Failed",
    createdAt: "2024-03-15",
  },
  {
    id: 4,
    fromChild: "Diana",
    coinAmount: 200,
    coinName: "Ripple",
    status: "Completed",
    createdAt: "2024-04-20",
  },
  {
    id: 5,
    fromChild: "Eve",
    coinAmount: 90,
    coinName: "Bitcoin Cash",
    status: "Pending",
    createdAt: "2024-05-30",
  },
];
