import {EnumUserRole, EnumUserStatus, EnumBuyCoinStatus, EnumCoinHistoryStatus} from "./enums";

// Creating an array of three user objects
export const fakeDataUsers = [
  {
    name: "Alice Johnson",
    email: `${EnumUserRole.admin}@email.com`,
    role: EnumUserRole.admin,
    permissions: ["read", "write", "delete"],
    id: 1,
    token: "token_123456",
    photo: "https://api.dicebear.com/9.x/dylan/svg?seed=Snuggles&hairColor=000000&mood=happy",
    password: `123456`,
    status: EnumUserStatus.active,
    phone: "01125963552",
  },
  {
    name: "Bob Smith",
    email: `${EnumUserRole.user}@email.com`,
    role: EnumUserRole.user,
    permissions: ["read"],
    id: 2,
    token: "token_654321",
    photo: "https://api.dicebear.com/9.x/dylan/svg?seed=Dusty&hairColor=000000&mood=happy",
    password: `123456`,
    status: EnumUserStatus.inactive,
    phone: "0125875220",
  },
];

export const fakeDataBuyCoinHistory = [
  {
    id: 1,
    address: "123 Main St",
    coinAmount: 0.5,
    coinName: "Bitcoin",
    paymentType: "Credit Card",
    status: EnumBuyCoinStatus.completed,
    createdAt: "2024-09-03T12:00:00Z",
  },
  {
    id: 2,
    address: "456 Oak Ave",
    coinAmount: 1.25,
    coinName: "Ethereum",
    paymentType: "PayPal",
    status: EnumBuyCoinStatus.pending,
    createdAt: "2024-09-02T14:30:00Z",
  },
  {
    id: 3,
    address: "789 Pine Rd",
    coinAmount: 0.75,
    coinName: "Litecoin",
    paymentType: "Bank Transfer",
    status: EnumBuyCoinStatus.failed,
    createdAt: "2024-09-01T09:15:00Z",
  },
  {
    id: 4,
    address: "321 Birch Ln",
    coinAmount: 2.0,
    coinName: "Ripple",
    paymentType: "Debit Card",
    status: EnumBuyCoinStatus.completed,
    createdAt: "2024-08-31T16:45:00Z",
  },
  {
    id: 5,
    address: "654 Maple St",
    coinAmount: 0.1,
    coinName: "Bitcoin",
    paymentType: "Bank Transfer",
    status: EnumBuyCoinStatus.pending,
    createdAt: "2024-08-30T10:20:00Z",
  },
  {
    id: 6,
    address: "987 Cedar Blvd",
    coinAmount: 0.3,
    coinName: "Ethereum",
    paymentType: "Credit Card",
    status: EnumBuyCoinStatus.completed,
    createdAt: "2024-08-29T13:05:00Z",
  },
  {
    id: 7,
    address: "741 Walnut Dr",
    coinAmount: 1.5,
    coinName: "Litecoin",
    paymentType: "PayPal",
    status: EnumBuyCoinStatus.failed,
    createdAt: "2024-08-28T08:40:00Z",
  },
];

export const fakeDataSentCoinHistory = [
  {
    id: 1,
    sender: "Alice",
    receiver: "Bob",
    coinAmount: 10,
    coinName: "Bitcoin",
    status: EnumCoinHistoryStatus.accepted,
    createdAt: "2024-09-01T12:00:00Z",
  },
  {
    id: 2,
    sender: "Charlie",
    receiver: "Dana",
    coinAmount: 5,
    coinName: "Ethereum",
    status: EnumCoinHistoryStatus.pending,
    createdAt: "2024-09-02T14:30:00Z",
  },
  {
    id: 3,
    sender: "Eve",
    receiver: "Frank",
    coinAmount: 20,
    coinName: "Litecoin",
    status: EnumCoinHistoryStatus.failed,
    createdAt: "2024-09-02T16:45:00Z",
  },
  {
    id: 4,
    sender: "Grace",
    receiver: "Heidi",
    coinAmount: 8,
    coinName: "Ripple",
    status: EnumCoinHistoryStatus.accepted,
    createdAt: "2024-09-03T09:15:00Z",
  },
  {
    id: 5,
    sender: "Ivan",
    receiver: "Judy",
    coinAmount: 12,
    coinName: "Cardano",
    status: EnumCoinHistoryStatus.pending,
    createdAt: "2024-09-03T11:30:00Z",
  },
  {
    id: 6,
    sender: "Karl",
    receiver: "Liam",
    coinAmount: 7,
    coinName: "Polkadot",
    status: EnumCoinHistoryStatus.accepted,
    createdAt: "2024-09-04T08:00:00Z",
  },
  {
    id: 7,
    sender: "Mona",
    receiver: "Nina",
    coinAmount: 15,
    coinName: "Chainlink",
    status: EnumCoinHistoryStatus.failed,
    createdAt: "2024-09-04T10:20:00Z",
  },
];

export const fakeDataWallets = [
  {
    label: "Select Wallet",
    value: "",
    disabled: true,
  },
  {
    label: "USDT",
    value: "USDT",
  },
  {
    label: "USDC",
    value: "USDC",
  },
  {
    label: "DAI",
    value: "DAI",
  },
];

export const fakeDataMyWallets = [
  {
    id: 1,
    name: "Bitcoin",
    coinType: "BTC",
    balance: 1.2345,
    updatedAt: "2024-09-01",
    userName: "Alice",
    userEmail: "jUwZx@example.com",
  },
  {
    id: 2,
    name: "Ethereum",
    coinType: "ETH",
    balance: 10.6789,
    updatedAt: "2024-09-02",
    userName: "Bob",
    userEmail: "jUwZx@example.com",
  },
  {
    id: 3,
    name: "Ripple",
    coinType: "XRP",
    balance: 5000.1234,
    updatedAt: "2024-09-03",
    userName: "Charlie",
    userEmail: "jUwZx@example.com",
  },
  {
    id: 4,
    name: "Litecoin",
    coinType: "LTC",
    balance: 250.5678,
    updatedAt: "2024-09-04",
    userName: "Dana",
    userEmail: "jUwZx@example.com",
  },
  {
    id: 5,
    name: "Cardano",
    coinType: "ADA",
    balance: 10000.9876,
    updatedAt: "2024-09-05",
    userName: "Eve",
    userEmail: "jUwZx@example.com",
  },
];

export const fakeDataSwapHistory = [
  {
    id: 1,
    fromWallet: "Wallet A",
    toWallet: "Wallet B",
    requestedAmount: 100.0,
    convertedAmount: 98.5,
    rate: 0.985,
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: 2,
    fromWallet: "Wallet C",
    toWallet: "Wallet D",
    requestedAmount: 200.0,
    convertedAmount: 196.0,
    rate: 0.98,
    createdAt: "2024-09-02T11:00:00Z",
  },
  {
    id: 3,
    fromWallet: "Wallet E",
    toWallet: "Wallet F",
    requestedAmount: 150.0,
    convertedAmount: 147.0,
    rate: 0.98,
    createdAt: "2024-09-03T12:00:00Z",
  },
  {
    id: 4,
    fromWallet: "Wallet G",
    toWallet: "Wallet H",
    requestedAmount: 300.0,
    convertedAmount: 294.0,
    rate: 0.98,
    createdAt: "2024-09-04T13:00:00Z",
  },
];


export const fakeDataReferrals = [
  {id: 1, level1: "Beginner", level2: "Intermediate", level3: "Advanced"},
  {id: 2, level1: "Basic", level2: "Skilled", level3: "Expert"},
  {id: 3, level1: "Entry", level2: "Proficient", level3: "Master"},
];

export const fakeDataReferences = [
  {
    id: 1,
    fullName: "John Doe",
    email: "john.doe@example.com",
    level: "Intermediate",
    joiningDate: "2022-01-15",
    balance: 1500.5,
    isActive: true,
  },
  {
    id: 2,
    fullName: "Jane Smith",
    email: "jane.smith@example.com",
    level: "Advanced",
    joiningDate: "2021-06-23",
    balance: 2300.75,
    isActive: false,
  },
  {
    id: 3,
    fullName: "Alice Johnson",
    email: "alice.johnson@example.com",
    level: "Beginner",
    joiningDate: "2023-03-10",
    balance: 890.0,
    isActive: true,
  },
  {
    id: 4,
    fullName: "Bob Williams",
    email: "bob.williams@example.com",
    level: "Expert",
    joiningDate: "2019-11-04",
    balance: 3200.25,
    isActive: true,
  },
];

export const fakeDataEarnings = [
  {
    id: 1,
    fromChild: "Alice",
    coinAmount: 50,
    coinName: "Bitcoin",
    status: "Completed",
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    fromChild: "Bob",
    coinAmount: 120,
    coinName: "Ethereum",
    status: "Pending",
    createdAt: "2024-02-05",
  },
  {
    id: 3,
    fromChild: "Charlie",
    coinAmount: 75,
    coinName: "Litecoin",
    status: "Failed",
    createdAt: "2024-03-15",
  },
  {
    id: 4,
    fromChild: "Diana",
    coinAmount: 200,
    coinName: "Ripple",
    status: "Completed",
    createdAt: "2024-04-20",
  },
  {
    id: 5,
    fromChild: "Eve",
    coinAmount: 90,
    coinName: "Bitcoin Cash",
    status: "Pending",
    createdAt: "2024-05-30",
  },
];

export const fakeDataUsersList = [
  {
    id: 1,
    userName: "johndoe",
    email: "john@example.com",
    role: "Admin",
    status: "Active",
    createdAt: "2023-08-01",
    phoneNumber: "123-456-7890",
    firstName: "John",
    lastName: "Doe",
  },
  {
    id: 2,
    userName: "janesmith",
    email: "jane@example.com",
    role: "User",
    status: "Inactive",
    createdAt: "2023-07-21",
    phoneNumber: "234-567-8901",
    firstName: "Jane",
    lastName: "Smith",
  },
  {
    id: 3,
    userName: "tomjohnson",
    email: "tom@example.com",
    role: "Judge",
    status: "Active",
    createdAt: "2023-06-15",
    phoneNumber: "345-678-9012",
    firstName: "Tom",
    lastName: "Johnson",
  },
  {
    id: 4,
    userName: "emilybrown",
    email: "emily@example.com",
    role: "User",
    status: "Pending",
    createdAt: "2023-09-10",
    phoneNumber: "456-789-0123",
    firstName: "Emily",
    lastName: "Brown",
  },
  {
    id: 5,
    userName: "michaelgreen",
    email: "michael@example.com",
    role: "Admin",
    status: "Inactive",
    createdAt: "2023-05-28",
    phoneNumber: "567-890-1234",
    firstName: "Michael",
    lastName: "Green",
  },
];

export const fakeDataCoinsList = [
  {
    id: 1,
    coinName: "Bitcoin",
    coinType: "Cryptocurrency",
    minWithdrawAmount: 0.001,
    maxWithdrawAmount: 10,
    feesPercentage: 0.5,
    status: "Active",
    updatedAt: "2024-09-14",
  },
  {
    id: 2,
    coinName: "Ethereum",
    coinType: "Cryptocurrency",
    minWithdrawAmount: 0.01,
    maxWithdrawAmount: 50,
    feesPercentage: 0.4,
    status: "Active",
    updatedAt: "2024-09-13",
  },
  {
    id: 3,
    coinName: "USDT",
    coinType: "Stablecoin",
    minWithdrawAmount: 5,
    maxWithdrawAmount: 10000,
    feesPercentage: 0.2,
    status: "Pending",
    updatedAt: "2024-09-12",
  },
  {
    id: 4,
    coinName: "Litecoin",
    coinType: "Cryptocurrency",
    minWithdrawAmount: 0.1,
    maxWithdrawAmount: 100,
    feesPercentage: 0.3,
    status: "Inactive",
    updatedAt: "2024-09-10",
  },
  {
    id: 5,
    coinName: "BNB",
    coinType: "Utility Token",
    minWithdrawAmount: 0.05,
    maxWithdrawAmount: 500,
    feesPercentage: 0.25,
    status: "Active",
    updatedAt: "2024-09-11",
  },
  {
    id: 6,
    coinName: "XRP",
    coinType: "Cryptocurrency",
    minWithdrawAmount: 20,
    maxWithdrawAmount: 1000,
    feesPercentage: 0.15,
    status: "Active",
    updatedAt: "2024-09-09",
  },
];

export const fakeDataBuyCoinOrders = [
  {
    email: "user1@example.com",
    coinAmount: 10,
    payableCoin: 9.5,
    paymentType: "Bitcoin",
    address: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    date: "2024-09-18",
    id: "TX001",
    status: "Completed",
  },
  {
    email: "user2@example.com",
    coinAmount: 15,
    payableCoin: 14.8,
    paymentType: "Ethereum",
    address: "0xAbc12345Def67890GhiJklMnOpq12345",
    date: "2024-09-17",
    id: "TX002",
    status: "Pending",
  },
  {
    email: "user3@example.com",
    coinAmount: 20,
    payableCoin: 19.9,
    paymentType: "Litecoin",
    address: "LcKuT1TGF9JydXVb3fAfqkYm8gHsAzzefQ",
    date: "2024-09-16",
    id: "TX003",
    status: "Failed",
  },
  {
    email: "user4@example.com",
    coinAmount: 50,
    payableCoin: 49.5,
    paymentType: "Ripple",
    address: "rDgY9SbbdXghUNJ6sBxTsQZLfQwHmM2cz",
    date: "2024-09-15",
    id: "TX004",
    status: "Completed",
  },
  {
    email: "user5@example.com",
    coinAmount: 5,
    payableCoin: 4.9,
    paymentType: "Bitcoin",
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    date: "2024-09-14",
    id: "TX005",
    status: "Pending",
  },
  {
    email: "user6@example.com",
    coinAmount: 100,
    payableCoin: 99.8,
    paymentType: "Ethereum",
    address: "0x12345Def67890GhiJklMnOpq12345Abc",
    date: "2024-09-13",
    id: "TX006",
    status: "Completed",
  },
];

export const fakeDataWithdrawalsRequests = [
  {
    id: 1,
    type: "Transfer",
    sender: "User1",
    coinType: "Bitcoin",
    address: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    receiver: "User2",
    amount: 0.5,
    fees: 0.0001,
    transactionId: "tx12345",
    updateDate: "2024-09-18",
    status: "Completed",
  },
  {
    id: 2,
    type: "Transfer",
    sender: "User3",
    coinType: "Ethereum",
    address: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e",
    receiver: "User4",
    amount: 10,
    fees: 0.005,
    transactionId: "tx67890",
    updateDate: "2024-09-18",
    status: "Pending",
  },
  {
    id: 3,
    type: "Deposit",
    sender: "User5",
    coinType: "Litecoin",
    address: "Lb6UMnMcWmXq9A9UkZ4ccHkmgYiKLY5HZV",
    receiver: "User6",
    amount: 15,
    fees: 0.002,
    transactionId: "tx11223",
    updateDate: "2024-09-17",
    status: "Completed",
  },
  {
    id: 4,
    type: "Withdrawal",
    sender: "User7",
    coinType: "Ripple",
    address: "rEXAMPLEr34X2X4X5X6X7XEXAMPLEpEXAMPLE",
    receiver: "User8",
    amount: 25,
    fees: 0.01,
    transactionId: "tx44556",
    updateDate: "2024-09-16",
    status: "Failed",
  },
  {
    id: 5,
    type: "Transfer",
    sender: "User9",
    coinType: "Dogecoin",
    address: "DBXu2kgc3xtvCUWFcxFE3r9hEYgmuaaCyD",
    receiver: "User10",
    amount: 500,
    fees: 0.1,
    transactionId: "tx78901",
    updateDate: "2024-09-15",
    status: "Completed",
  },
  {
    id: 6,
    type: "Deposit",
    sender: "User11",
    coinType: "Bitcoin Cash",
    address: "qq7z9e0vl9aw9ex9u9z9qq7z9e0vl9aw9ex9u9z9",
    receiver: "User12",
    amount: 2,
    fees: 0.0005,
    transactionId: "tx22334",
    updateDate: "2024-09-14",
    status: "Pending",
  },
];

export const fakeDataPlansList = [
  {
    id: 1,
    planName: "Basic Plan",
    minimumAmount: 100,
    duration: "30 days",
    bonusType: "Fixed",
    bonus: 5,
    bonusCoinType: "Bitcoin",
    status: "Active",
    createdAt: "2024-09-18",
  },
  {
    id: 2,
    planName: "Silver Plan",
    minimumAmount: 500,
    duration: "60 days",
    bonusType: "Percentage",
    bonus: 10,
    bonusCoinType: "Ethereum",
    status: "Inactive",
    createdAt: "2024-08-10",
  },
  {
    id: 3,
    planName: "Gold Plan",
    minimumAmount: 1000,
    duration: "90 days",
    bonusType: "Fixed",
    bonus: 50,
    bonusCoinType: "Litecoin",
    status: "Active",
    createdAt: "2024-07-25",
  },
  {
    id: 4,
    planName: "Platinum Plan",
    minimumAmount: 5000,
    duration: "120 days",
    bonusType: "Percentage",
    bonus: 15,
    bonusCoinType: "Ripple",
    status: "Active",
    createdAt: "2024-06-12",
  },
  {
    id: 5,
    planName: "Diamond Plan",
    minimumAmount: 10000,
    duration: "180 days",
    bonusType: "Fixed",
    bonus: 100,
    bonusCoinType: "Bitcoin Cash",
    status: "Inactive",
    createdAt: "2024-05-30",
  },
];
